export default {
	installation: {
		data: [
			{
				id: 1,
				name: "@versini/ui-styles",
				description:
					"Required package to handle styles via TailwindCSS, including Typography.",
			},
			{
				id: 2,
				name: "@versini/ui-icons",
				description: "All the icons used in the UI-Components library.",
			},
			{
				id: 3,
				name: "@versini/ui-system",
				description:
					"System level components such as Flexgrid and ThemeProvider.",
			},
		],
	},
	components: {
		data: [
			{
				id: 1,
				character: "Paul Atreides",
				actor: "Timothée Chalamet",
				timestamp: "10/17/2023 08:46 PM EDT",
			},
			{
				id: 2,
				character: "Lady Jessica",
				actor: "Rebecca Ferguson",
				timestamp: "10/16/2023 08:55 PM EDT",
			},
			{
				id: 3,
				character: "Duncan Idaho",
				actor: "Jason Momoa",
				timestamp: "10/16/2023 08:59 PM EDT",
			},
		],
		nutritionData: [
			{
				id: 1,
				name: "Cupcake",
				calories: 305,
				fat: 3.7,
				carbs: 67,
				protein: 4.3,
			},
			{
				id: 2,
				name: "Donut",
				calories: 452,
				fat: 25.0,
				carbs: 51,
				protein: 4.9,
			},
			{
				id: 3,
				name: "Eclair",
				calories: 262,
				fat: 16.0,
				carbs: 24,
				protein: 6.0,
			},
			{
				id: 4,
				name: "Frozen yoghurt",
				calories: 159,
				fat: 6.0,
				carbs: 24,
				protein: 4.0,
			},
			{
				id: 5,
				name: "Gingerbread",
				calories: 356,
				fat: 16.0,
				carbs: 49,
				protein: 3.9,
			},
			{
				id: 6,
				name: "Honeycomb",
				calories: 408,
				fat: 3.2,
				carbs: 87,
				protein: 6.5,
			},
			{
				id: 7,
				name: "Ice cream sandwich",
				calories: 237,
				fat: 9.0,
				carbs: 37,
				protein: 4.3,
			},
			{
				id: 8,
				name: "Jelly Bean",
				calories: 375,
				fat: 0.0,
				carbs: 94,
				protein: 0.0,
			},
			{
				id: 9,
				name: "KitKat",
				calories: 518,
				fat: 26.0,
				carbs: 65,
				protein: 7.0,
			},
			{
				id: 10,
				name: "Lollipop",
				calories: 392,
				fat: 0.2,
				carbs: 98,
				protein: 0.0,
			},
			{
				id: 11,
				name: "Marshmallow",
				calories: 318,
				fat: 0,
				carbs: 81,
				protein: 2.0,
			},
			{
				id: 12,
				name: "Nougat",
				calories: 360,
				fat: 19.0,
				carbs: 9,
				protein: 37.0,
			},
			{
				id: 13,
				name: "Oreo",
				calories: 437,
				fat: 18.0,
				carbs: 63,
				protein: 4.0,
			},
		],
		stickyData: [
			{
				id: 1,
				timestamp: "10/16/2023 08:46 PM EDT",
				character: "Who plays Paul Atreides?",
				actor: "Timothée Chalamet",
			},
			{
				id: 2,
				timestamp: "10/16/2023 08:55 PM EDT",
				character: "What about Lady Jessica?",
				actor: "Rebecca Ferguson",
			},
			{
				id: 3,
				timestamp: "10/16/2023 08:59 PM EDT",
				character: "And Duncan Idaho?",
				actor: "Jason Momoa",
			},
			{
				id: 4,
				timestamp: "10/16/2023 08:59 PM EDT",
				character: "And Duncan Idaho?",
				actor: "Jason Momoa",
			},
			{
				id: 5,
				timestamp: "10/16/2023 08:59 PM EDT",
				character: "And Duncan Idaho?",
				actor: "Jason Momoa",
			},
			{
				id: 6,
				timestamp: "10/16/2023 08:59 PM EDT",
				character: "And Duncan Idaho?",
				actor: "Jason Momoa",
			},
			{
				id: 7,
				timestamp: "10/16/2023 08:59 PM EDT",
				character: "And Duncan Idaho?",
				actor: "Jason Momoa",
			},
		],
	},
};
